### ISSUE TITLE
Remove off-heap buffers

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-ruby#10]
# Roadmap

Ruby types to transform: (Items are sorted from the easiest to the hardest.)

-   [ ] `T_STRING`: off-heap array of non-reference byte data
-   [ ] `T_ARRAY`: off-heap array of references
-   [ ] `T_HASH`: off-heap hash table
-   [ ] `T_OBJECT`: off-heap array plus hash table
-   [ ] `T_DATA`: user-defined types.  Maybe we can use non-resurrecting finalization instead, but only if the `data` pointer never changes.
    -   [ ] `RData`:
    -   [ ] `RTypedData`:
-   [ ] other types.

# Rationale

In Ruby, almost all object types are subject to finalization (i.e. calling `obj_free` on the object when the object dies).  This is not normal.

Most of the time, Ruby call `obj_free` to free underlying off-heap buffers allocated using `xmalloc`.  Vanilla Ruby does this **because their GC cannot allocate objects larger than 40 bytes (extended to 320 bytes with RVARGC)**.  MMTk doesn't have such limitation.

We should fix this problem by **transforming those off-heap buffers into on-heap objects**.

## Attached type information of buffers

To scan those buffers, the buffers must have attached type information, in the form of `struct RBasic`.  We may add a special `ruby_value_type`, such as `RUBY_T_MMTK = 0x17`, to indicate it is special MMTk-specific objects, and should be scanned specially.

An alternative approach is to keep those buffers "naked" (without header), and extend mmtk-core to support such objects.  Julia also has such "naked" buffers.
