### ISSUE TITLE
Roadmap to the proper support of finalisation

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-ruby#2]
Task list:

-   [x] Properly support non-resurrecting finalisation (Ruby `ObjectSpace.define_finalizer`)
    -   ~~Treat "zombies" like `PhantomReference`~~
        We will stop using mmtk-core's Java-style reference handling.  Instead we'll use the new binding-side reference/finaliser processing API.
        -   ~~`PhantomReference` support in `mmtk-core` (Done: https://github.com/mmtk/mmtk-core/pull/564)~~
    -   [X] Create ~~"zombie"~~ "finalisation job" when a finaliser is added
        -   I choose not to call it "zombie" because they do not reuse the space of dead objects, and I invented my own structure that is very different to `RZombie`.
    -   [X] Execute "finalisation jobs" periodically
    -   [x] Execute "finalisation jobs" at exit
-   [x] Properly support resurrecting finalisation (any non-trivial actions in `obj_free`, especially `T_DATA`, `T_FILE` and `T_SYMBOL`)
    -   ~~`mmtk-core` supports getting object registered for finalisation before the object dies. (https://github.com/mmtk/mmtk-core/pull/578)~~
        We will stop using mmtk-core's Java-style reference handling.  Instead we'll use the new binding-side reference/finaliser processing API.  https://github.com/mmtk/mmtk-core/pull/700
    -   [X] ~~Decouple the  `Finalization` work packet from`ProcessEdgesWork` to support object enqueuing.~~ 
            We don't need special handling in `Finalization`. The current Java-style finalization mechanism supports Ruby well.
            -   https://github.com/wks/mmtk-ruby/tree/gen-weakref-api
            -   https://github.com/wks/ruby/tree/gen-weakref-api
        -   [X] `mmtk-core` support `ProcessObjectsWork` in addition to `ProcessEdgesWork`. 
            -   Issue: https://github.com/mmtk/mmtk-core/issues/581
            -   PR: https://github.com/mmtk/mmtk-core/pull/628 (merged)
    -   [x] Add a hook on the Ruby side.  When GC triggered during heap allocation (`mmtk_alloc`), we run non-resurrecting finalizers (`obj_free`).

**Comment by wks** [comment]
While working on supporting VM binding-side reference/finaliser handling, I managed to handle finalisers (`ObjectSpace.define_finalizer`) by traversing the `finalizer_table` and creating "finalisation job" (our own alternative to zombies) for dead entries.  Now those finalisers can be properly executed after GC is triggered.

**Comment by wks** [comment]
I think we now fully support finalisers, at least on my experimental branch.

- https://github.com/wks/mmtk-core/tree/gen-weakref-api
- https://github.com/wks/mmtk-ruby/tree/gen-weakref-api
- https://github.com/wks/ruby/tree/gen-weakref-api

**Comment by wks** [comment]
The gen-weakref-api branches listed above have been merged.  Closing this issue...
