### ISSUE TITLE
Roadmap to a fully functional Ruby VM with MMTk

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-ruby#20]
This is a very high level roadmap.

-   [X] Step 1: Support NoGC
-   [X] Step 2: Support MarkSweep and non-copying Immix
    -   Tracking issue: https://github.com/mmtk/mmtk-ruby/issues/3
-   [ ] Step 3: Support copying Immix
    -   Tracking issue: https://github.com/mmtk/mmtk-ruby/issues/18
-   [ ] Intermediate step: Remove excessive `obj_free`
    -   Tracking issue: https://github.com/mmtk/mmtk-ruby/issues/11
-   [ ] Step 4: Support StickyImmix, a generational collector
    -   Main challenge: write-barrier-unprotected (WB-unprotected) objects
-   [ ] Step 5: Implement allocation and write barrier fast paths with YJIT
