### ISSUE TITLE
Roadmap to proper mark-sweep support

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-ruby#3]
The Ruby binding currently supports MarkSweep, but in a very hacky way.  MMTk's tracing algorithm is edge-centric, in the sense that the tracing process is described by work packets that handle lists of edges.  However, Ruby traces one object at a time.  This requires us to change the way mmtk-core does tracing.  The stack-scanning interface is also tightly-coupled with the `ProcessEdgesWork` work packet, which is unsuitable for Ruby.

-   [X] Support node enqueuing. https://github.com/mmtk/mmtk-core/issues/581
-   [X] Support node-based stack scanning.  ~~https://github.com/mmtk/mmtk-core/pull/598~~, https://github.com/mmtk/mmtk-core/pull/611

Dependencies:
-   [X] ~~Eliminate the `ProcessEdgesWork` trait.  With this, it is difficult to scan stacks for nodes. https://github.com/mmtk/mmtk-core/issues/599~~ We worked around this problem temporarily by creating an empty `ProcessEdgesWork` packet and use it to create `ScanObjects` work packet.  We may redesign the tracing framework in the future.
    -   [x] Simplify `trace_object`.  Part of it is removing the `TransitiveClosure` trait which `ProcessEdgesWork` inherits.  https://github.com/mmtk/mmtk-core/issues/559

**Comment by wks** [comment]
Now tracing is implemented fully in mmtk-core.  The tracing code in mmtk-ruby is removed.
