### ISSUE TITLE
Roadmap: Support StickyImmix

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-ruby#57]
This issue tracks the progress of supporting StickyImmix, a generational collector.

-   Write barrier
    -   [X] Routing RB_OBJ_WRITE and RB_OBJ_WRITTEN to MMTk barrier implementation
    -   [X] Map `rb_gc_writebarrier_remember` so that MMTk remembers the object
    -   bulk array access
        -   [X] Use `rb_gc_writebarrier_remember` to remember parent array.
        -   [ ] Change to region barrier if possible.
-   WB-unprotected objects
    -   [X] Registering
    -   [X] Scanning
    -   [ ] Checking if an object is WB-unprotected
    -   [ ] Unregistering
-   Testing
    -   [X] Tests pass with object movement disabled
    -   [ ] Tests pass with object movement enabled
    -   [ ] Test with Liquid benchmark
-   Performance
    -   TODO
